# Generated by Django 5.0.6 on 2024-09-07 16:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_name', models.BinaryField(blank=True, null=True)),
                ('encrypted_description', models.BinaryField(blank=True, null=True)),
                ('encrypted_notes', models.BinaryField(blank=True, null=True)),
                ('solvent', models.CharField(blank=True, default='Ethanol', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's Formula",
                'verbose_name_plural': "User's Formulae",
                'db_table': 'formulae',
                'ordering': ['user', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FormulaIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('unit', models.CharField(default='g', max_length=50, verbose_name='Unit')),
                ('percentage', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
                ('collection_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.regularcollectioningredient')),
                ('custom_collection_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.customcollectioningredient')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='formulae.formula')),
            ],
            options={
                'verbose_name': 'Ingredient in Formula',
                'verbose_name_plural': 'Ingredients in Formula',
                'db_table': 'formula_ingredients',
                'ordering': ['formula', 'collection_ingredient__ingredient__common_name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='formula',
            name='tags',
            field=models.ManyToManyField(blank=True, to='formulae.tag'),
        ),
    ]
