# Generated by Django 5.0.6 on 2024-09-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_newcollectioningredient_unique_together_and_more'),
        ('formulae', '0002_newformula_newformulaingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='newformulaingredient',
            name='counterpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.newcollectioningredient'),
        ),
    ]
