# Generated by Django 5.0.3 on 2024-04-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("formulae", "0003_rename_ingformula_formulaingredient_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formula",
            options={
                "ordering": ["user", "name"],
                "verbose_name": "User's Formula",
                "verbose_name_plural": "User's Formulae",
            },
        ),
        migrations.AlterModelTable(
            name="formulaingredient",
            table="formula_ingredients",
        ),
    ]
