# Generated by Django 5.0.4 on 2024-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulae", "0011_remove_formula_custom_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="notes",
            field=models.TextField(blank=True, default="nothing here"),
        ),
        migrations.AlterField(
            model_name="formula",
            name="description",
            field=models.TextField(blank=True, default="nothing here"),
        ),
    ]
