# Generated by Django 5.0.4 on 2024-05-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulae', '0013_alter_formula_options_alter_formula_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formula',
            unique_together=set(),
        ),
    ]
