# Generated by Django 5.0.4 on 2024-05-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulae", "0014_alter_formula_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="solvent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
