# Generated by Django 5.0.3 on 2024-04-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulae', '0005_alter_formulaingredient_formula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formula',
            options={'ordering': ['user', '-updated_at', '-name'], 'verbose_name': "User's Formula", 'verbose_name_plural': "User's Formulae"},
        ),
    ]
