name: bcf-build

services:
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile
    env_file:
      - ./svelte/.env

  axum:
    build:
      context: ./axum
      dockerfile: Dockerfile
      args:
        RUSTFLAGS: "-C target-cpu=native"
    env_file:
      - ./axum/.env
