services:
  svelte:
    image: ghcr.io/noxlovette/bcf-prod-svelte:v1.0.9
    container_name: bcf-prod-svelte
    env_file:
      - ./.env.svelte
    ports:
      - "3334:3000"
    networks:
      - web
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis/redis-stack-server:latest
    container_name: bcf-prod-redis
    restart: unless-stopped
    networks:
      - web
      - internal

  axum:
    image: ghcr.io/noxlovette/bcf-prod-axum:v1.0.1
    container_name: bcf-prod-axum
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./.env.axum
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  postgres:
    image: postgres:17-alpine
    container_name: bcf-prod-pg
    restart: unless-stopped
    ports:
      - "5440:5432"
    env_file: ./.env.postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  db-data:
    name: db-bcf-prod

networks:
  web:
    name: web-bcf
  internal:
    name: internal-bcf
    internal: true
