services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env
    restart: always
    depends_on:
      - backend

  redis:
    image: redis/redis-stack:latest
    container_name: redis-bcf
    ports:
      - "6379:6379"
      - "8001:8001"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${PGNAME}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_PORT=${PGPORT}
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${PGNAME:-bcf}
      - POSTGRES_USER=${PGUSER:-postgres}
      - POSTGRES_PASSWORD=${PGPASSWORD:-your_secure_password}
      - PGPORT=${PGPORT:-5432}
      - PGHOST=${PGHOST:-db}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
