name: bcf-dev

services:
  svelte:
    container_name: svelte-bcf-dev
    build:
      context: ./svelte
      dockerfile: Dockerfile.dev
    ports:
      - "5174:3000"
    volumes:
      - ./svelte:/app
    env_file:
      - ./svelte/.env
    depends_on:
      - django

  redis:
    image: redis/redis-stack:latest
    container_name: redis-bcf
    ports:
      - "6379:6379"
      - "8001:8001"

  django:
    container_name: django-bcf-dev
    build:
      context: ./django
      dockerfile: Dockerfile.dev
    volumes:
      - ./django:/app
    env_file:
      - ./django/.env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    container_name: pg-bcf-dev
    restart: always
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pg-bcf-dev
      - POSTGRES_PASSWORD=changeme

    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    name: db-bcf-dev
