# Generated by Django 5.1.4 on 2024-12-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_rename_newcollectioningredient_collectioningredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioningredient',
            name='common_name',
            field=models.CharField(default='New Ingredient', max_length=255, verbose_name='Common Name'),
        ),
    ]
