# Generated by Django 5.0.2 on 2024-03-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_app', '0004_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Families'},
        ),
        migrations.AlterModelTable(
            name='family',
            table='family',
        ),
    ]
