# Generated by Django 5.0.3 on 2024-03-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_app', '0008_alter_ingredient_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='IFRA',
        ),
    ]
