# Generated by Django 5.0.6 on 2024-09-07 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('browse', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCollectionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='g', max_length=50, verbose_name='Unit')),
                ('is_collection', models.BooleanField(default=False, verbose_name='In Collection')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('encrypted_impression', models.BinaryField(blank=True, null=True)),
                ('encrypted_colour', models.BinaryField(blank=True, null=True)),
                ('encrypted_associations', models.BinaryField(blank=True, null=True)),
                ('encrypted_ideas', models.BinaryField(blank=True, null=True)),
                ('encrypted_common_name', models.BinaryField(blank=True, null=True)),
                ('encrypted_cas', models.BinaryField(blank=True, null=True)),
                ('encrypted_use', models.BinaryField(blank=True, null=True)),
                ('encrypted_volatility', models.BinaryField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Ingredient',
                'verbose_name_plural': 'Custom Ingredients',
                'db_table': 'custom_collection_ing',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='RegularCollectionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='g', max_length=50, verbose_name='Unit')),
                ('is_collection', models.BooleanField(default=False, verbose_name='In Collection')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('encrypted_impression', models.BinaryField(blank=True, null=True)),
                ('encrypted_colour', models.BinaryField(blank=True, null=True)),
                ('encrypted_associations', models.BinaryField(blank=True, null=True)),
                ('encrypted_ideas', models.BinaryField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.ingredient')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingredient in Collection',
                'verbose_name_plural': 'Ingredients in Collection',
                'db_table': 'user_collection_ing',
                'ordering': ['user', 'ingredient__common_name'],
                'unique_together': {('user', 'ingredient')},
            },
        ),
    ]
