# Generated by Django 5.0.6 on 2024-09-09 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcollectioningredient',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True, null=True),
        ),
        migrations.AddField(
            model_name='regularcollectioningredient',
            name='uuid',
            field=models.UUIDField(editable=False, unique=True, null=True),
        ),
    ]
