# Generated by Django 5.1.4 on 2024-12-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collectioningredient_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioningredient',
            name='origin',
            field=models.TextField(blank=True, null=True, verbose_name='Origin'),
        ),
    ]
