# Generated by Django 5.0.3 on 2024-03-20 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_alter_usercollectioning_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usercollectioning",
            table="user_collection_ing",
        ),
    ]
