# Generated by Django 5.0.6 on 2024-09-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_newcollectioningredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcollectioningredient',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='newcollectioningredient',
            name='other_names',
            field=models.TextField(blank=True, null=True, verbose_name='Other Names'),
        ),
        migrations.AlterField(
            model_name='newcollectioningredient',
            name='use',
            field=models.TextField(blank=True, null=True, verbose_name='Use'),
        ),
        migrations.AlterField(
            model_name='newcollectioningredient',
            name='volatility',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Volatility'),
        ),
    ]
