# Generated by Django 5.0.6 on 2024-09-10 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_alter_newcollectioningredient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newcollectioningredient',
            unique_together={('user', 'id')},
        ),
        migrations.AlterField(
            model_name='newcollectioningredient',
            name='cas',
            field=models.CharField(default='0000-00-0', max_length=100, verbose_name='CAS'),
        ),
        migrations.AlterField(
            model_name='newcollectioningredient',
            name='common_name',
            field=models.CharField(default='New Ingredient', max_length=100, verbose_name='Common Name'),
        ),
        migrations.AlterField(
            model_name='newcollectioningredient',
            name='descriptors',
            field=models.CharField(default='New Ingredient', max_length=100, verbose_name='Descriptors'),
        ),
    ]
