# Generated by Django 5.0.4 on 2024-04-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0009_customcollectioningredient_use_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectioningredient",
            old_name="notes",
            new_name="ideas",
        ),
        migrations.RenameField(
            model_name="customcollectioningredient",
            old_name="notes",
            new_name="ideas",
        ),
    ]
