# Generated by Django 5.0.4 on 2024-05-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0012_collectioningredient_encrypted_impression_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectioningredient",
            options={
                "ordering": ["user", "ingredient__common_name"],
                "verbose_name": "Ingredient in Collection",
                "verbose_name_plural": "Ingredients in Collection",
            },
        ),
        migrations.AlterModelOptions(
            name="customcollectioningredient",
            options={
                "ordering": ["user"],
                "verbose_name": "Custom Ingredient",
                "verbose_name_plural": "Custom Ingredients",
            },
        ),
        migrations.RemoveField(
            model_name="collectioningredient",
            name="associations",
        ),
        migrations.RemoveField(
            model_name="collectioningredient",
            name="colour",
        ),
        migrations.RemoveField(
            model_name="collectioningredient",
            name="ideas",
        ),
        migrations.RemoveField(
            model_name="collectioningredient",
            name="impression",
        ),
        migrations.RemoveField(
            model_name="customcollectioningredient",
            name="associations",
        ),
        migrations.RemoveField(
            model_name="customcollectioningredient",
            name="cas",
        ),
        migrations.RemoveField(
            model_name="customcollectioningredient",
            name="colour",
        ),
        migrations.RemoveField(
            model_name="customcollectioningredient",
            name="common_name",
        ),
        migrations.RemoveField(
            model_name="customcollectioningredient",
            name="ideas",
        ),
        migrations.RemoveField(
            model_name="customcollectioningredient",
            name="impression",
        ),
        migrations.RemoveField(
            model_name="customcollectioningredient",
            name="use",
        ),
        migrations.RemoveField(
            model_name="customcollectioningredient",
            name="volatility",
        ),
        migrations.AddField(
            model_name="collectioningredient",
            name="encrypted_associations",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collectioningredient",
            name="encrypted_colour",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collectioningredient",
            name="encrypted_ideas",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customcollectioningredient",
            name="encrypted_associations",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customcollectioningredient",
            name="encrypted_cas",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customcollectioningredient",
            name="encrypted_colour",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customcollectioningredient",
            name="encrypted_common_name",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customcollectioningredient",
            name="encrypted_ideas",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customcollectioningredient",
            name="encrypted_use",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collectioningredient",
            name="amount",
            field=models.FloatField(default=0, verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="customcollectioningredient",
            name="amount",
            field=models.FloatField(default=0, verbose_name="Amount"),
        ),
    ]
