# Generated by Django 5.0.4 on 2024-05-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0013_alter_collectioningredient_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customcollectioningredient",
            name="encrypted_volatility",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
