FROM rust:latest
WORKDIR /app

RUN apt-get update && apt-get install -y pkg-config libssl-dev
RUN cargo install cargo-watch 
RUN cargo install sqlx-cli --no-default-features --features postgres

CMD ["export DATABASE_URL=postgres://postgres:changeme@db:5432/pg-bcf-dev"]
CMD ["cargo", "watch", "-x", "run --bin rust"]