# Generated by Django 5.0.3 on 2024-03-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectioning',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='usercollectioning',
            name='unit',
            field=models.CharField(default='g', max_length=50, verbose_name='Unit'),
        ),
    ]
