# Generated by Django 5.0.6 on 2024-09-07 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Descriptor',
                'verbose_name_plural': 'Descriptors',
                'db_table': 'descriptors',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200, verbose_name='Name')),
                ('other_names', models.TextField(blank=True, null=True, verbose_name='Other Names')),
                ('cas', models.CharField(blank=True, max_length=30, null=True, verbose_name='CAS')),
                ('ingredient_type', models.CharField(choices=[('synthetic', 'Synthetic'), ('natural', 'Natural'), ('base', 'Base')], max_length=15, null=True, verbose_name='Type')),
                ('use', models.TextField(blank=True, null=True, verbose_name='Use')),
                ('volatility', models.CharField(blank=True, max_length=20, null=True, verbose_name='Volatility')),
                ('is_restricted', models.BooleanField(default=False, null=True, verbose_name='Restricted')),
                ('origin', models.TextField(blank=True, null=True, verbose_name='Origin')),
                ('constituents', models.ManyToManyField(blank=True, to='browse.ingredient', verbose_name='Constituents')),
                ('contributors', models.ManyToManyField(related_name='contributors', to=settings.AUTH_USER_MODEL)),
                ('descriptor1', models.ManyToManyField(related_name='descriptor1', to='browse.descriptor', verbose_name='Descriptor 1')),
                ('descriptor2', models.ManyToManyField(related_name='descriptor2', to='browse.descriptor', verbose_name='Descriptor 2')),
                ('descriptor3', models.ManyToManyField(related_name='descriptor3', to='browse.descriptor', verbose_name='Descriptor 3')),
                ('similar_ingredients', models.ManyToManyField(blank=True, to='browse.ingredient', verbose_name='Similar Ingredients')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredients',
                'unique_together': {('cas', 'common_name')},
            },
        ),
        migrations.CreateModel(
            name='SuggestedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(default='unchanged', max_length=200, verbose_name='Name')),
                ('other_names', models.TextField(blank=True, default='unchanged', null=True, verbose_name='Other Names')),
                ('cas', models.CharField(blank=True, default='unchanged', max_length=30, null=True, verbose_name='CAS')),
                ('ingredient_type', models.CharField(default='unchanged', max_length=15, null=True, verbose_name='Type')),
                ('use', models.TextField(blank=True, default=1, null=True, verbose_name='Use')),
                ('volatility', models.CharField(blank=True, default='unchanged', max_length=20, null=True, verbose_name='Volatility')),
                ('is_restricted', models.BooleanField(default=None, null=True, verbose_name='Restricted')),
                ('origin', models.TextField(blank=True, default='unchanged', null=True, verbose_name='Origin')),
                ('constituents', models.TextField(blank=True, default='unchanged', null=True, verbose_name='Constituents')),
                ('similar_ingredients', models.TextField(blank=True, default=None, null=True, verbose_name='Similar Ingredients')),
                ('message', models.TextField(blank=True, null=True)),
                ('date_suggested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ingredient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='browse.ingredient')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'suggested ingredient',
                'verbose_name_plural': 'suggested ingredients',
                'db_table': 'suggested_ingredients',
            },
        ),
    ]
