# Generated by Django 5.0.2 on 2024-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_alter_ingredient_cas_alter_ingredient_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='is_collection',
            field=models.BooleanField(default=False, null=True, verbose_name='In Collection'),
        ),
    ]
