# Generated by Django 5.1.1 on 2024-09-17 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "browse",
            "0006_rename_similar_ingredients_suggestedingredient_related_ingredients_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestedingredient",
            name="is_restricted",
            field=models.TextField(
                default="unchanged", null=True, verbose_name="Restricted"
            ),
        ),
        migrations.AlterField(
            model_name="suggestedingredient",
            name="use",
            field=models.TextField(
                blank=True, default="unchanged", null=True, verbose_name="Use"
            ),
        ),
        migrations.AlterField(
            model_name="suggestedingredient",
            name="user",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
