# Generated by Django 5.0.4 on 2024-04-23 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0016_remove_ingredient_latin_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedIngredient',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='browse.ingredient')),
            ],
            bases=('browse.ingredient',),
        ),
    ]
