# Generated by Django 5.0.6 on 2024-09-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0004_alter_ingredient_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="similar_ingredients",
            new_name="related_ingredients",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="constituents",
        ),
    ]
