# Generated by Django 5.1.1 on 2024-09-17 08:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0001_initial"),
        ("formulae", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewFormula",
            new_name="Formula",
        ),
        migrations.RenameModel(
            old_name="NewFormulaIngredient",
            new_name="FormulaIngredient",
        ),
    ]
