# Generated by Django 5.1.1 on 2024-09-17 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0002_rename_newcollectioningredient_collectioningredient"),
        ("formulae", "0002_rename_newformula_formula_formulaingredient_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formulaingredient",
            options={
                "ordering": ["formula", "volatility"],
                "verbose_name": "Ingredient in Formula",
                "verbose_name_plural": "Ingredients in Formula",
            },
        ),
        migrations.AlterField(
            model_name="formulaingredient",
            name="counterpart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="counterpart",
                to="collection.collectioningredient",
            ),
        ),
        migrations.AlterModelTable(
            name="formulaingredient",
            table="formula_ingredients",
        ),
    ]
